version: "3.8"

services:
    traefik:
        image: traefik:v2.3
        command:
            #- "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedByDefault=false"
            - "--entrypoints.web.address=:80"
            #- "--log.level=DEBUG"
            #- "--api.dashboard=true"
        #labels:
        #    - "entryPoints.web.forwardedHeaders.insecure"
        #    - "entryPoints.web.proxyProtocol.insecure"
        #    - "traefik.http.routers.traefik.rule=Host(`traefik.mdesoeuv.com`)"
        #    - "traefik.http.routers.traefik.service=api@internal"
        #    - "traefik.http.routers.traefik.entrypoints=websecure"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - wordpress

    wordpress:
        container_name: wordpress
        labels:
            - "traefik.enable=true"
            - "entryPoints.web.forwardedHeaders.insecure"
            - "entryPoints.web.proxyProtocol.insecure"
            - "traefik.http.routers.wordpress.rule=Host(`cloud.mdesoeuv.com`)"
            - "traefik.http.services.wordpress.loadbalancer.server.port=80"
            - "traefik.http.routers.wordpress.entrypoints=websecure"


        working_dir: /var/www/html
        image: wordpress:latest
        restart: always
        environment:
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DEBUG: 1
        healthcheck:
            test: [ "CMD", "curl", "--fail", "http://localhost" ]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 15s
        volumes:
            - wp_data:/var/www/html
        networks:
            - wordpress

    phpmyadmin:
        container_name: phpmyadmin
        labels:
            - "traefik.enable=true"
            - "entryPoints.web.forwardedHeaders.insecure"
            - "entryPoints.web.proxyProtocol.insecure"
            - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.mdesoeuv.com`)"
            - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
            - "traefik.http.routers.phpmyadmin.entrypoints=websecure"

        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_ABSOLUTE_URI: "https://phpmyadmin.mdesoeuv.com"
        networks:
            - wordpress

    wpcli:
        container_name: wpcli
        working_dir: /var/www/html
        image: wordpress:cli
        depends_on:
            wordpress:
                condition: service_healthy
        environment:
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_USER: ${MYSQL_USER}
        user: xfs
        entrypoint: [ "wp", "--allow-root" ]
        command: >
            core install --path="/var/www/html" --url=${WP_URL} --title="${WP_TITLE}" --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASSWORD} --admin_email=${WP_ADMIN_EMAIL}; wp --allow-root plugin install server-ip-memory-usage --activate
        volumes:
            - wp_data:/var/www/html
        networks:
            - wordpress

    wpcli-plugin:
        container_name: wpcli-plugin
        working_dir: /var/www/html
        image: wordpress:cli
        depends_on:
            wpcli:
                condition: service_completed_successfully
        environment:
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_USER: ${MYSQL_USER}
        user: xfs
        entrypoint: [ "wp", "--allow-root" ]
        command: >
            plugin install server-ip-memory-usage --activate
        volumes:
            - wp_data:/var/www/html
        networks:
            - wordpress

    wpcli-plugin-2:
        container_name: wpcli-plugin-2
        working_dir: /var/www/html
        image: wordpress:cli
        depends_on:
            wpcli-plugin:
                condition: service_completed_successfully
        environment:
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_TABLE_PREFIX: wp_
            WORDPRESS_DB_USER: ${MYSQL_USER}
        user: xfs
        entrypoint: [ "wp", "--allow-root" ]
        command: >
            plugin install classic-editor --activate
        volumes:
            - wp_data:/var/www/html
        networks:
            - wordpress

volumes:
    wp_data:


networks:
    wordpress:


